// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etisopnidkyjlbedkswq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0aXNvcG5pZGt5amxiZWRrc3dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMTAyNDYsImV4cCI6MjA1ODc4NjI0Nn0.5aX_mJy3sUfgHrYDHo4b1y4aETz4l5_fBt-Rq-acXkE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);